### ISSUE TITLE
为什么现在图标都只能显示默认的了?

### ISSUE THREAD

**Issue by dcdb723** [niu541412/easy_switch#4]
如题

**Comment by niu541412** [comment]
什么插件版本，什么版本浏览器，什么操作系统？
我这边三个浏览器，在macOS windows，Firefox， Edge, Chrome 显示都正常

**Comment by dcdb723** [comment]
> 什么插件版本，什么版本浏览器，什么操作系统？ 我这边三个浏览器，在macOS windows，Firefox， Edge, Chrome 显示都正常

mac 14.5, edge, v3.0.2.
不记得什么时候开始没不显示图标了
<img width="212" alt="image" src="https://github.com/niu541412/easy_switch/assets/19933213/85a827cc-e47b-410d-8bb9-d76e0ecde9de">

**Comment by dcdb723** [comment]
哦,嗨,是新版本多了个按钮样式选择吧?默认好像就那个,我换成嵌套的就有了,不知道有这功能😂

**Comment by niu541412** [comment]
默认应该是和以前一样的，只是我最近换了个插件的默认图标，之前那个比较粗糙。也不适合非中文的用户。

**Comment by niu541412** [comment]
我发现了原生图标的确有问题，v3.0.3今天会修复。

**Comment by dcdb723** [comment]
> 我发现了原生图标的确有问题，v3.0.3今天会修复。

666🤙
